#ifndef LIBSM64GD_SM64SURFACEPROPERTIES_H
#define LIBSM64GD_SM64SURFACEPROPERTIES_H

#include <godot_cpp/classes/resource.hpp>
#include <godot_cpp/core/binder_common.hpp>

#include <libsm64/src/decomp/include/surface_terrains.h>

#ifdef WIN32
#include <windows.h>
#endif

class SM64SurfaceProperties : public godot::Resource
{
    GDCLASS(SM64SurfaceProperties, godot::Resource);

public:
    SM64SurfaceProperties() = default;

    enum SurfaceType {
        SURFACE_TYPE_DEFAULT                  = SURFACE_DEFAULT,
        SURFACE_TYPE_BURNING                  = SURFACE_BURNING,
        SURFACE_TYPE_0004                     = SURFACE_0004,
        SURFACE_TYPE_HANGABLE                 = SURFACE_HANGABLE,
        SURFACE_TYPE_SLOW                     = SURFACE_SLOW,
        SURFACE_TYPE_DEATH_PLANE              = SURFACE_DEATH_PLANE,
        SURFACE_TYPE_CLOSE_CAMERA             = SURFACE_CLOSE_CAMERA,
        SURFACE_TYPE_WATER                    = SURFACE_WATER,
        SURFACE_TYPE_FLOWING_WATER            = SURFACE_FLOWING_WATER,
        SURFACE_TYPE_INTANGIBLE               = SURFACE_INTANGIBLE,
        SURFACE_TYPE_VERY_SLIPPERY            = SURFACE_VERY_SLIPPERY,
        SURFACE_TYPE_SLIPPERY                 = SURFACE_SLIPPERY,
        SURFACE_TYPE_NOT_SLIPPERY             = SURFACE_NOT_SLIPPERY,
        SURFACE_TYPE_TTM_VINES                = SURFACE_TTM_VINES,
        SURFACE_TYPE_MGR_MUSIC                = SURFACE_MGR_MUSIC,
        SURFACE_TYPE_INSTANT_WARP_1B          = SURFACE_INSTANT_WARP_1B,
        SURFACE_TYPE_INSTANT_WARP_1C          = SURFACE_INSTANT_WARP_1C,
        SURFACE_TYPE_INSTANT_WARP_1D          = SURFACE_INSTANT_WARP_1D,
        SURFACE_TYPE_INSTANT_WARP_1E          = SURFACE_INSTANT_WARP_1E,
        SURFACE_TYPE_SHALLOW_QUICKSAND        = SURFACE_SHALLOW_QUICKSAND,
        SURFACE_TYPE_DEEP_QUICKSAND           = SURFACE_DEEP_QUICKSAND,
        SURFACE_TYPE_INSTANT_QUICKSAND        = SURFACE_INSTANT_QUICKSAND,
        SURFACE_TYPE_DEEP_MOVING_QUICKSAND    = SURFACE_DEEP_MOVING_QUICKSAND,
        SURFACE_TYPE_SHALLOW_MOVING_QUICKSAND = SURFACE_SHALLOW_MOVING_QUICKSAND,
        SURFACE_TYPE_QUICKSAND                = SURFACE_QUICKSAND,
        SURFACE_TYPE_MOVING_QUICKSAND         = SURFACE_MOVING_QUICKSAND,
        SURFACE_TYPE_WALL_MISC                = SURFACE_WALL_MISC,
        SURFACE_TYPE_NOISE_DEFAULT            = SURFACE_NOISE_DEFAULT,
        SURFACE_TYPE_NOISE_SLIPPERY           = SURFACE_NOISE_SLIPPERY,
        SURFACE_TYPE_HORIZONTAL_WIND          = SURFACE_HORIZONTAL_WIND,
        SURFACE_TYPE_INSTANT_MOVING_QUICKSAND = SURFACE_INSTANT_MOVING_QUICKSAND,
        SURFACE_TYPE_ICE                      = SURFACE_ICE,
        SURFACE_TYPE_LOOK_UP_WARP             = SURFACE_LOOK_UP_WARP,
        SURFACE_TYPE_HARD                     = SURFACE_HARD,
        SURFACE_TYPE_WARP                     = SURFACE_WARP,
        SURFACE_TYPE_TIMER_START              = SURFACE_TIMER_START,
        SURFACE_TYPE_TIMER_END                = SURFACE_TIMER_END,
        SURFACE_TYPE_HARD_SLIPPERY            = SURFACE_HARD_SLIPPERY,
        SURFACE_TYPE_HARD_VERY_SLIPPERY       = SURFACE_HARD_VERY_SLIPPERY,
        SURFACE_TYPE_HARD_NOT_SLIPPERY        = SURFACE_HARD_NOT_SLIPPERY,
        SURFACE_TYPE_VERTICAL_WIND            = SURFACE_VERTICAL_WIND,
        SURFACE_TYPE_BOSS_FIGHT_CAMERA        = SURFACE_BOSS_FIGHT_CAMERA,
        SURFACE_TYPE_CAMERA_FREE_ROAM         = SURFACE_CAMERA_FREE_ROAM,
        SURFACE_TYPE_THI3_WALLKICK            = SURFACE_THI3_WALLKICK,
        SURFACE_TYPE_CAMERA_8_DIR             = SURFACE_CAMERA_8_DIR,
        SURFACE_TYPE_CAMERA_MIDDLE            = SURFACE_CAMERA_MIDDLE,
        SURFACE_TYPE_CAMERA_ROTATE_RIGHT      = SURFACE_CAMERA_ROTATE_RIGHT,
        SURFACE_TYPE_CAMERA_ROTATE_LEFT       = SURFACE_CAMERA_ROTATE_LEFT,
        SURFACE_TYPE_CAMERA_BOUNDARY          = SURFACE_CAMERA_BOUNDARY,
        SURFACE_TYPE_NOISE_VERY_SLIPPERY_73   = SURFACE_NOISE_VERY_SLIPPERY_73,
        SURFACE_TYPE_NOISE_VERY_SLIPPERY_74   = SURFACE_NOISE_VERY_SLIPPERY_74,
        SURFACE_TYPE_NOISE_VERY_SLIPPERY      = SURFACE_NOISE_VERY_SLIPPERY,
        SURFACE_TYPE_NO_CAM_COLLISION         = SURFACE_NO_CAM_COLLISION,
        SURFACE_TYPE_NO_CAM_COLLISION_77      = SURFACE_NO_CAM_COLLISION_77,
        SURFACE_TYPE_NO_CAM_COL_VERY_SLIPPERY = SURFACE_NO_CAM_COL_VERY_SLIPPERY,
        SURFACE_TYPE_NO_CAM_COL_SLIPPERY      = SURFACE_NO_CAM_COL_SLIPPERY,
        SURFACE_TYPE_SWITCH                   = SURFACE_SWITCH,
        SURFACE_TYPE_VANISH_CAP_WALLS         = SURFACE_VANISH_CAP_WALLS,
        SURFACE_TYPE_PAINTING_WOBBLE_A6       = SURFACE_PAINTING_WOBBLE_A6,
        SURFACE_TYPE_PAINTING_WOBBLE_A7       = SURFACE_PAINTING_WOBBLE_A7,
        SURFACE_TYPE_PAINTING_WOBBLE_A8       = SURFACE_PAINTING_WOBBLE_A8,
        SURFACE_TYPE_PAINTING_WOBBLE_A9       = SURFACE_PAINTING_WOBBLE_A9,
        SURFACE_TYPE_PAINTING_WOBBLE_AA       = SURFACE_PAINTING_WOBBLE_AA,
        SURFACE_TYPE_PAINTING_WOBBLE_AB       = SURFACE_PAINTING_WOBBLE_AB,
        SURFACE_TYPE_PAINTING_WOBBLE_AC       = SURFACE_PAINTING_WOBBLE_AC,
        SURFACE_TYPE_PAINTING_WOBBLE_AD       = SURFACE_PAINTING_WOBBLE_AD,
        SURFACE_TYPE_PAINTING_WOBBLE_AE       = SURFACE_PAINTING_WOBBLE_AE,
        SURFACE_TYPE_PAINTING_WOBBLE_AF       = SURFACE_PAINTING_WOBBLE_AF,
        SURFACE_TYPE_PAINTING_WOBBLE_B0       = SURFACE_PAINTING_WOBBLE_B0,
        SURFACE_TYPE_PAINTING_WOBBLE_B1       = SURFACE_PAINTING_WOBBLE_B1,
        SURFACE_TYPE_PAINTING_WOBBLE_B2       = SURFACE_PAINTING_WOBBLE_B2,
        SURFACE_TYPE_PAINTING_WOBBLE_B3       = SURFACE_PAINTING_WOBBLE_B3,
        SURFACE_TYPE_PAINTING_WOBBLE_B4       = SURFACE_PAINTING_WOBBLE_B4,
        SURFACE_TYPE_PAINTING_WOBBLE_B5       = SURFACE_PAINTING_WOBBLE_B5,
        SURFACE_TYPE_PAINTING_WOBBLE_B6       = SURFACE_PAINTING_WOBBLE_B6,
        SURFACE_TYPE_PAINTING_WOBBLE_B7       = SURFACE_PAINTING_WOBBLE_B7,
        SURFACE_TYPE_PAINTING_WOBBLE_B8       = SURFACE_PAINTING_WOBBLE_B8,
        SURFACE_TYPE_PAINTING_WOBBLE_B9       = SURFACE_PAINTING_WOBBLE_B9,
        SURFACE_TYPE_PAINTING_WOBBLE_BA       = SURFACE_PAINTING_WOBBLE_BA,
        SURFACE_TYPE_PAINTING_WOBBLE_BB       = SURFACE_PAINTING_WOBBLE_BB,
        SURFACE_TYPE_PAINTING_WOBBLE_BC       = SURFACE_PAINTING_WOBBLE_BC,
        SURFACE_TYPE_PAINTING_WOBBLE_BD       = SURFACE_PAINTING_WOBBLE_BD,
        SURFACE_TYPE_PAINTING_WOBBLE_BE       = SURFACE_PAINTING_WOBBLE_BE,
        SURFACE_TYPE_PAINTING_WOBBLE_BF       = SURFACE_PAINTING_WOBBLE_BF,
        SURFACE_TYPE_PAINTING_WOBBLE_C0       = SURFACE_PAINTING_WOBBLE_C0,
        SURFACE_TYPE_PAINTING_WOBBLE_C1       = SURFACE_PAINTING_WOBBLE_C1,
        SURFACE_TYPE_PAINTING_WOBBLE_C2       = SURFACE_PAINTING_WOBBLE_C2,
        SURFACE_TYPE_PAINTING_WOBBLE_C3       = SURFACE_PAINTING_WOBBLE_C3,
        SURFACE_TYPE_PAINTING_WOBBLE_C4       = SURFACE_PAINTING_WOBBLE_C4,
        SURFACE_TYPE_PAINTING_WOBBLE_C5       = SURFACE_PAINTING_WOBBLE_C5,
        SURFACE_TYPE_PAINTING_WOBBLE_C6       = SURFACE_PAINTING_WOBBLE_C6,
        SURFACE_TYPE_PAINTING_WOBBLE_C7       = SURFACE_PAINTING_WOBBLE_C7,
        SURFACE_TYPE_PAINTING_WOBBLE_C8       = SURFACE_PAINTING_WOBBLE_C8,
        SURFACE_TYPE_PAINTING_WOBBLE_C9       = SURFACE_PAINTING_WOBBLE_C9,
        SURFACE_TYPE_PAINTING_WOBBLE_CA       = SURFACE_PAINTING_WOBBLE_CA,
        SURFACE_TYPE_PAINTING_WOBBLE_CB       = SURFACE_PAINTING_WOBBLE_CB,
        SURFACE_TYPE_PAINTING_WOBBLE_CC       = SURFACE_PAINTING_WOBBLE_CC,
        SURFACE_TYPE_PAINTING_WOBBLE_CD       = SURFACE_PAINTING_WOBBLE_CD,
        SURFACE_TYPE_PAINTING_WOBBLE_CE       = SURFACE_PAINTING_WOBBLE_CE,
        SURFACE_TYPE_PAINTING_WOBBLE_CF       = SURFACE_PAINTING_WOBBLE_CF,
        SURFACE_TYPE_PAINTING_WOBBLE_D0       = SURFACE_PAINTING_WOBBLE_D0,
        SURFACE_TYPE_PAINTING_WOBBLE_D1       = SURFACE_PAINTING_WOBBLE_D1,
        SURFACE_TYPE_PAINTING_WOBBLE_D2       = SURFACE_PAINTING_WOBBLE_D2,
        SURFACE_TYPE_PAINTING_WARP_D3         = SURFACE_PAINTING_WARP_D3,
        SURFACE_TYPE_PAINTING_WARP_D4         = SURFACE_PAINTING_WARP_D4,
        SURFACE_TYPE_PAINTING_WARP_D5         = SURFACE_PAINTING_WARP_D5,
        SURFACE_TYPE_PAINTING_WARP_D6         = SURFACE_PAINTING_WARP_D6,
        SURFACE_TYPE_PAINTING_WARP_D7         = SURFACE_PAINTING_WARP_D7,
        SURFACE_TYPE_PAINTING_WARP_D8         = SURFACE_PAINTING_WARP_D8,
        SURFACE_TYPE_PAINTING_WARP_D9         = SURFACE_PAINTING_WARP_D9,
        SURFACE_TYPE_PAINTING_WARP_DA         = SURFACE_PAINTING_WARP_DA,
        SURFACE_TYPE_PAINTING_WARP_DB         = SURFACE_PAINTING_WARP_DB,
        SURFACE_TYPE_PAINTING_WARP_DC         = SURFACE_PAINTING_WARP_DC,
        SURFACE_TYPE_PAINTING_WARP_DD         = SURFACE_PAINTING_WARP_DD,
        SURFACE_TYPE_PAINTING_WARP_DE         = SURFACE_PAINTING_WARP_DE,
        SURFACE_TYPE_PAINTING_WARP_DF         = SURFACE_PAINTING_WARP_DF,
        SURFACE_TYPE_PAINTING_WARP_E0         = SURFACE_PAINTING_WARP_E0,
        SURFACE_TYPE_PAINTING_WARP_E1         = SURFACE_PAINTING_WARP_E1,
        SURFACE_TYPE_PAINTING_WARP_E2         = SURFACE_PAINTING_WARP_E2,
        SURFACE_TYPE_PAINTING_WARP_E3         = SURFACE_PAINTING_WARP_E3,
        SURFACE_TYPE_PAINTING_WARP_E4         = SURFACE_PAINTING_WARP_E4,
        SURFACE_TYPE_PAINTING_WARP_E5         = SURFACE_PAINTING_WARP_E5,
        SURFACE_TYPE_PAINTING_WARP_E6         = SURFACE_PAINTING_WARP_E6,
        SURFACE_TYPE_PAINTING_WARP_E7         = SURFACE_PAINTING_WARP_E7,
        SURFACE_TYPE_PAINTING_WARP_E8         = SURFACE_PAINTING_WARP_E8,
        SURFACE_TYPE_PAINTING_WARP_E9         = SURFACE_PAINTING_WARP_E9,
        SURFACE_TYPE_PAINTING_WARP_EA         = SURFACE_PAINTING_WARP_EA,
        SURFACE_TYPE_PAINTING_WARP_EB         = SURFACE_PAINTING_WARP_EB,
        SURFACE_TYPE_PAINTING_WARP_EC         = SURFACE_PAINTING_WARP_EC,
        SURFACE_TYPE_PAINTING_WARP_ED         = SURFACE_PAINTING_WARP_ED,
        SURFACE_TYPE_PAINTING_WARP_EE         = SURFACE_PAINTING_WARP_EE,
        SURFACE_TYPE_PAINTING_WARP_EF         = SURFACE_PAINTING_WARP_EF,
        SURFACE_TYPE_PAINTING_WARP_F0         = SURFACE_PAINTING_WARP_F0,
        SURFACE_TYPE_PAINTING_WARP_F1         = SURFACE_PAINTING_WARP_F1,
        SURFACE_TYPE_PAINTING_WARP_F2         = SURFACE_PAINTING_WARP_F2,
        SURFACE_TYPE_PAINTING_WARP_F3         = SURFACE_PAINTING_WARP_F3,
        SURFACE_TYPE_TTC_PAINTING_1           = SURFACE_TTC_PAINTING_1,
        SURFACE_TYPE_TTC_PAINTING_2           = SURFACE_TTC_PAINTING_2,
        SURFACE_TYPE_TTC_PAINTING_3           = SURFACE_TTC_PAINTING_3,
        SURFACE_TYPE_PAINTING_WARP_F7         = SURFACE_PAINTING_WARP_F7,
        SURFACE_TYPE_PAINTING_WARP_F8         = SURFACE_PAINTING_WARP_F8,
        SURFACE_TYPE_PAINTING_WARP_F9         = SURFACE_PAINTING_WARP_F9,
        SURFACE_TYPE_PAINTING_WARP_FA         = SURFACE_PAINTING_WARP_FA,
        SURFACE_TYPE_PAINTING_WARP_FB         = SURFACE_PAINTING_WARP_FB,
        SURFACE_TYPE_PAINTING_WARP_FC         = SURFACE_PAINTING_WARP_FC,
        SURFACE_TYPE_WOBBLING_WARP            = SURFACE_WOBBLING_WARP,
        SURFACE_TYPE_TRAPDOOR                 = SURFACE_TRAPDOOR
    };

    enum TerrainType {
        TERRAIN_TYPE_GRASS  = TERRAIN_GRASS,
        TERRAIN_TYPE_STONE  = TERRAIN_STONE,
        TERRAIN_TYPE_SNOW   = TERRAIN_SNOW,
        TERRAIN_TYPE_SAND   = TERRAIN_SAND,
        TERRAIN_TYPE_SPOOKY = TERRAIN_SPOOKY,
        TERRAIN_TYPE_WATER  = TERRAIN_WATER,
        TERRAIN_TYPE_SLIDE  = TERRAIN_SLIDE,
        TERRAIN_TYPE_MASK   = TERRAIN_MASK
    };

    void set_surface_type(SurfaceType value);
    SurfaceType get_surface_type() const;

    void set_terrain_type(TerrainType value);
    TerrainType get_terrain_type() const;

    void set_force(int value);
    int get_force() const;

protected:
    static void _bind_methods();

private:
    SurfaceType surface_type = SURFACE_TYPE_DEFAULT;
    TerrainType terrain_type = TERRAIN_TYPE_GRASS;
    int force = 0;
};

VARIANT_ENUM_CAST(SM64SurfaceProperties::SurfaceType);
VARIANT_ENUM_CAST(SM64SurfaceProperties::TerrainType);

#endif // LIBSM64GD_SM64SURFACEPROPERTIES_H